language: php

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: bionic
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

before_install:
  - composer validate --no-check-all --strict

install:
  - composer install --ignore-platform-reqs
  - composer update $PREFER_LOWEST

before_script:
  - # FOSSA 许可校验
    "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash"

script:
  - fossa init
  - fossa analyze
  - composer ci

after_success:
  - git config user.name "DongyunLee"
  - git config user.email "dongyunli619@gmail.com"
  - git add .
  - git commit -m "Test And Build"
#  - git push --force --quiet "https://${GH_TOKEN}@github.com/nim-lang-cn/website.git" master:master

cache:
  - packages