language: php

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: bionic

script:
  - composer ci

after_success:
  - cd dist/
  - git init
  - git config user.name "DongyunLee"
  - git config user.email "dongyunli619@gmail.com"
  - git add .
  - git commit -m "Test And Build"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/DongyunLee/SM3-PHP.git" master:pre-build

branches:
  except:
    - pre-build
